### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by alisterburt** [alisterburt/tomo_preprocessing#13]
This is an issue to track things that we consider essential before concluding this chapter

- [ ] Check that TSA metadata is correctly generated from AreTomo alignment and can be used to reconstruct tomograms using RELION
- [ ] Independent, easy to run installation checks for both AreTomo and IMOD
- [ ] creating downsampled images for faster visualisation
- [ ] interactive tilt-image exclusion job
- [ ] Etomo launcher, allowing to further refine/optimise an IMOD tilt-series alignment
- [ ] particle picking (simple points, dipoles, spheres, surfaces, filaments, tubes)
- [ ] integrate everything into RELION GUI
- [ ] add CCP-EM pipeliner job types

cc @EuanPyle

**Comment by inter1965** [comment]
Are there patches for relion's motioncor & ctf estimation jobs?

**Comment by EuanPyle** [comment]
Yep, these are in the process of being implemented but aren't quite ready yet.

**Comment by alisterburt** [comment]
To clarify, there are already patches for motioncor, none for ctffind which is a simple wrapper around ctffind4

**Comment by EuanPyle** [comment]
Potential things to add:
A flip YZ/Z option in Tomogram Reconstruction? 
Denoising option also in Tomogram Reconstruction (I'm exploring cryoCARE at the moment)

**Comment by alisterburt** [comment]
I think we should avoid adding options for flipping to minimise the number of ways handedness can be inverted, keep it simple :)

Denoising after reconstruction will be useful but I don't consider it essential for a first release, go ahead though!

**Comment by inter1965** [comment]
How about multiple instance of aretomo when aligning tilt series?
Currently there's no option to pass to "relion_run_align_tiltseries", is it possible to make it work as "relion_run_motioncorr" to use different GPU simultaneously?

**Comment by alisterburt** [comment]
@inter1965 there's an MPI runner inside relion for aligning tilt-series in parallel - I haven't tested it for AreTomo though. @EuanPyle might have more info?

**Comment by EuanPyle** [comment]
Must admit I never have used multi GPU to run AreTomo, it's developed by the same people so I imagine it's possible to run in the same way...I'll look into it

**Comment by inter1965** [comment]
AreTomo has the same option "-Gpu" like MotionCor2 which specify which gpu to use, 
And there's also a "--gpu" option in relion's motioncor_runner (with or without _mpi) to specify "Device ids for each MPI-thread, e.g 0:1:2:3", however it lacks options to pass through between relion_run_align_tiltseries -> relion_tomo_align_tilt_series -> lil_aretomo  -> aretomo.

**Comment by EuanPyle** [comment]
I see, I will add GPU specification to lil_aretomo/relion_tomo_align_tilt_series and will ask for that option to be put into rln if it doesn't exist already.

**Comment by EuanPyle** [comment]
Forgot to update, this is working in tomo_PP and rln GUI as well. Currently number of GPUs must match number of MPI in rln so multiple GPUs aren't assigned to the same TS.

**Comment by alisterburt** [comment]
closing because development has moved to relion repo
